### ISSUE TITLE
connection aborted 10054

### ISSUE THREAD

**Issue by YakobovLior** [swar/nba_api#215]
Hello,
I noticed that starting few days ago, the NBA API is not accessible.
At first, I used the endpoint and tried to reach it with **requests** module.
I've tried from several computers, different user agents, all of the header variations but every time I get this error:

```
Traceback (most recent call last):
  File "scripts\get_teams.py", line 81, in <module>
    main()
  File "scripts\get_teams.py", line 73, in main
    list_team_ids = get_team_ids_list()
  File "scripts\get_teams.py", line 23, in get_team_ids_list
    response = requests.get(url, headers=HEADERS)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))
```

Later on, I tried to use **nba-api** library, and it did worked for the several first requests, but now using the library I get a new error:

```
Traceback (most recent call last):
  File "scripts\get_teams.py", line 30, in get_team_ids_list
    response = commonteamyears.CommonTeamYears(league_id='00')
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\nba_api\stats\endpoints\commonteamyears.py", line 30, in __init__
    self.get_request()
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\nba_api\stats\endpoints\commonteamyears.py", line 38, in get_request
    timeout=self.timeout,
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\nba_api\library\http.py", line 130, in send_api_request
    response = requests.get(url=base_url, params=parameters, headers=request_headers, proxies=proxies, timeout=timeout)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\liorya\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
```

Has someone else ran into this issue? if so, is there a way to fix it?
Could it be that NBA site blocks specific IP addresses if certain amount of request is being passed?

Thanks,
Lior

**Comment by rsforbes** [comment]
@YakobovLior: Are you still having issues?

**Comment by YakobovLior** [comment]
Hey @rsforbes 
No I managed to overcome this, the reason was throttling from NBA API so I reduced the amount of requests.

**Comment by rsforbes** [comment]
@YakobovLior - Thanks for the update. I've found that a delay of 600ms worked very well.
