### ISSUE TITLE
GameRotation might be broken?

### ISSUE THREAD

**Issue by shlomizadok** [swar/nba_api#232]
Hey I'm trying the following
```
from nba_api.stats.endpoints import GameRotation
game_rotation = GameRotation(game_id="0022100112", league_id=00)
```
And getting the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shlomizadok/Library/Python/3.8/lib/python/site-packages/nba_api/stats/endpoints/gamerotation.py", line 32, in __init__
    self.get_request()
  File "/Users/shlomizadok/Library/Python/3.8/lib/python/site-packages/nba_api/stats/endpoints/gamerotation.py", line 42, in get_request
    self.load_response()
  File "/Users/shlomizadok/Library/Python/3.8/lib/python/site-packages/nba_api/stats/endpoints/gamerotation.py", line 45, in load_response
    data_sets = self.nba_response.get_data_sets()
  File "/Users/shlomizadok/Library/Python/3.8/lib/python/site-packages/nba_api/stats/library/http.py", line 83, in get_data_sets
    raw_dict = self.get_dict()
  File "/Users/shlomizadok/Library/Python/3.8/lib/python/site-packages/nba_api/library/http.py", line 41, in get_dict
    return json.loads(self._response)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Not sure whether I do something wrong or is there an issue

**Comment by shlomizadok** [comment]
My bad! Should be 
`game_rotation = GameRotation(game_id="0022100112", league_id="00")`
(league_id...)
