### ISSUE TITLE
[Bug]: Unable to retrieve any team static data (nba_api.stats.static.teams has ImportErrors)

### ISSUE THREAD

**Issue by Nickatak** [swar/nba_api#287]
### NBA API Version

v1.1.12

### Issue

When attempting to import `get_teams` from `nba_api.stats.static.teams`, the line `from nba_api.stats.library.data import team_index_championship_year` is ran and thus fails (due to the absence of `team_index_championship_year` in `nba_api.stats.library.data`).

# Expected behavior:
I should be able to import `get_teams`  from `nba_api.stats.static.teams` and then use it to retrieve a list of teams.

# Actual behavior:
Runtime fails with[^1]:
```
Traceback (most recent call last):
  File "example\demonstration.py", line 1, in <module>
    from nba_api.stats.static.teams import get_teams
  File "example\venv\lib\site-packages\nba_api\stats\static\teams.py", line 5, in <module>
    from nba_api.stats.library.data import team_index_championship_year
ImportError: cannot import name 'team_index_championship_year' from 'nba_api.stats.library.data' (example\venv\lib\site-packages\nba_api\stats\library\data.py)
```

# Repro steps:
1. Create a new venv (`python -m venv venv`).
2. Activate the venv (Depends on your OS).
3. Install the latest version of nba_api (`pip install nba_api`) - this defaults to v1.1.12 as of the time of writing this bug report.
4. Create a file with the following contents:
```
from nba_api.stats.static.teams import get_teams

print(get_teams())
```
5. Run the file.
6. Examine given error above.

[^1]: I have stripped ONLY the user directories from the above traceback for privacy.

**Comment by Nickatak** [comment]
As I'm unfamiliar with basketball/the NBA's structure as a whole (I was hoping to use this package to learn a bit about it), I can't really suggest a solution here, as I'm not sure what the `team_index_championship_year` was supposed to be.  I can only assume that it was changed/moved at some point and didn't get updated in the static files.

**Comment by Nickatak** [comment]
This was fixed by https://github.com/swar/nba_api/pull/286 (https://github.com/swar/nba_api/pull/286/commits/11e238642d2286a62d3fba0b9e975eb811c46b25).  Thanks.
