### ISSUE TITLE
NBA API: timeout in /stats endpoints

### ISSUE THREAD

**Issue by sallareznov** [swar/nba_api#320]
Hello,

First, I cannot thank you enough for this wonderful library.

I believe this has already been addressed in previous issues, but still shooting my shot.
I'm having an issue with the NBA API for an app deployed on Heroku:
- the requests to `/stats` endpoints time out in production, while working locally
- the requests to `/live` endpoints work fine

I'm aware that NBA blocks its API for Heroku instances, but I wanted to know if you were able to find a long-term workaround for this.

I'm using the version `1.1.13` of the library.

Thanks in advance :)

**Comment by zbleszczak** [comment]
Hi, basically i have the same issue but not with ### /stats but with ### 'PlayerCareerStats' endpoint. 
I heard that upgrading versions to the newest would help, but i **already have this done**. I made request **timeout longer to 90s** but its still **Read timed out** situation every 9/10 situations.

**Comment by sallareznov** [comment]
> Hi, basically i have the same issue but not with /stats but with **_'PlayerCareerStats'_** endpoint. I heard that upgrading versions to the newest would help, but i **already have this done**. I made request **timeout longer to 90s** but its still **Read timed out** situation every 9/10 situations.

Yeah exactly :/

**Comment by akacaio** [comment]
Same here. I'm trying to access the traditional boxscore endpoint and this happened to me.

**Comment by pauldevos** [comment]
I believe the header requirements by nba.com/stats has changed. The parameters are often the same with a few different API changes, e.g. boxscoreadvancedv2 => boxscoreadvancedv3 (version 3)

```
https://stats.nba.com/stats/boxscoreadvancedv3?
    GameID=0022200701&LeagueID=00&endPeriod=0&endRange=28800&rangeType=0&startPeriod=0&startRange=0
```


But the parameters are the same, but doesn't work, gets a timeout issue. Which likely suggests the request header is an issue. I've tried 12 different endpoints and all get the same error. I'm using my laptop, so not a chunk of blocked AWS or Azure resources (which is a common issue with scraping).

When visiting the webpage directly and using the `inspect` element, I find the API and the Header. I then put those into code. But still having issues. Makes me wonder if need to capture the *Response Cookie*??

Here's an endpoint that is taken right from the inspector:
```
https://stats.nba.com/stats/leaguedashplayerptshot?CloseDefDistRange=&College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&DribbleRange=&GameScope=&GameSegment=&GeneralRange=Overall&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2022-23&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&ShotDistRange=&StarterBench=&TeamID=0&TouchTimeRange=&VsConference=&VsDivision=&Weight=
```

Put in header form:
```
headers = {
'Host': 'stats.nba.com',
'Connection': 'keep-alive',
'Accept': 'application/json, text/plain, */*',
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
'Origin': 'https://www.nba.com',
'Referer': 'https://www.nba.com/',
'Accept-Encoding': 'gzip, deflate, br',
'Accept-Language': 'en-US,en;q=0.5',
'Sec-Fetch-Dest': 'empty',
'Sec-Fetch-Mode': 'cors',
'Sec-Fetch-Site': 'same-site',
'Sec-GPC': '1'
}
```

<img width="1496" alt="Screen Shot 2023-01-28 at 10 49 25 PM" src="https://user-images.githubusercontent.com/6967308/215305614-3b8fcc75-29e1-4e3c-945a-3b4fe5e78ab1.png">

Anyone else had success?

**Comment by pauldevos** [comment]
I've also seen a 504 response, again this is using local [Mac], Jupyter Notebook Python requests package. But in actually going to the nba.com website, seeing the API endpoint in the Network traffic, it's the same. So something to do with a cookie and/or header is my guess.

**Comment by efiul** [comment]
Hi,
I have the same issue.

- the requests to /stats endpoints (for example 'https://stats.nba.com/stats/commonteamroster') time out in production, while working locally.
- the requests to /live endpoints work fine (for example 'https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json')

I am using version `1.1.11` of the library.
I tried to use different headers with no success.

Has anyone resolved this issue?
Thanks.

**Comment by Justin19960919** [comment]
Same issue here as @efiul

**Comment by OnerInce** [comment]
Since AWS/GCP/Heroku (maybe others too) IP addresses are blocked by NBA, a solution doesn't seem possible using Headers. Only possible solution as far as I know is using proxies while making requests.

**Comment by JoKuebler** [comment]
Some endpoints were working for me today but stopped after a bit. I turned on my VPN and it worked again. Seems like my IP gets blocked after a while which is weird since I didn't use it extensively.

**Comment by Justin19960919** [comment]
does anyone know how to use proxies? I looked up free proxies yesterday but none of them worked.
I passed in "{proxy}:{port}" in the proxy param for the call but connection still failed

**Comment by OnerInce** [comment]
> does anyone know how to use proxies? I looked up free proxies yesterday but none of them worked. I passed in "{proxy}:{port}" in the proxy param for the call but connection still failed

Its so difficult to find a free working proxy from the web. You can check out paid proxy services

**Comment by caseta** [comment]
Anyone figure this out with Heroku?

**Comment by ckim16** [comment]
has anyone resolved with streamlit by any chance?

**Comment by jacasta2** [comment]
I had a mix experience with Streamlit, sometimes it works, but some others it doesn't. I work mainly with the endpoints `leaguegamefinder.LeagueGameFinder()` and `boxscoretraditionalv2.BoxScoreTraditionalV2()`.

Now, I believe I'm facing this issue with GitHub Actions. I have a scheduled action to fetch recent games using the endpoint `leaguegamefinder.LeagueGameFinder()`. I'm testing it to fetch info from only 6 games (a 6-row dataframe), but I'm getting the following error:

```
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
```

This is the full trace:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/***/***/src/fetch_data.py", line 326, in <module>
    fetch_recent_games()
  File "/home/runner/work/***/***/src/fetch_data.py", line 260, in fetch_recent_games
    new_data_regular_season = leaguegamefinder.LeagueGameFinder(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nba_api/stats/endpoints/leaguegamefinder.py", line [20](https://github.com/jacasta2/nba_analysis/actions/runs/8010834757/job/21882723941#step:5:21)4, in __init__
    self.get_request()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nba_api/stats/endpoints/leaguegamefinder.py", line 207, in get_request
    self.nba_response = NBAStatsHTTP().send_api_request(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nba_api/library/http.py", line 1[30](https://github.com/jacasta2/nba_analysis/actions/runs/8010834757/job/21882723941#step:5:31), in send_api_request
    response = requests.get(url=base_url, params=parameters, headers=request_headers, proxies=proxies, timeout=timeout)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/adapters.py", line 5[32](https://github.com/jacasta2/nba_analysis/actions/runs/8010834757/job/21882723941#step:5:33), in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=4[43](https://github.com/jacasta2/nba_analysis/actions/runs/8010834757/job/21882723941#step:5:44)): Read timed out. (read timeout=30)
```

What a buzzkiller!
