### ISSUE TITLE
[Bug]: playbyplayv3 throws an error when unpacking the 

### ISSUE THREAD

**Issue by equilibliam** [swar/nba_api#433]
### NBA API Version

1.4.1

### Issue

When attempting to fetch play-by-play data using the playbyplayv3.PlayByPlayV3() method from the nba_api library, a TypeError is raised indicating that NBAStatsResponse.get_data_sets() takes 1 positional argument but 2 were given.

Thanks for all the work on this library - it is so so so useful.

### Code

import pandas as pd
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playbyplayv3
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.library.parameters import Season
from nba_api.stats.library.parameters import SeasonType
from sqlalchemy import create_engine
# Define a function to fetch play by play data for a game
def fetch_play_by_play(game_id):
    play_by_play_data = playbyplayv3.PlayByPlayV3(game_id)
    play_by_play_data = playbyplaydata.get_data_frames()[0]
    return play_by_play_data

# Define a function to fetch all games in the past 3 years
def fetch_games_past_3_years():
    gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable=Season.default, season_type_nullable=SeasonType.regular)
    all_games = gamefinder.get_data_frames()[0]
    all_games['GAME_DATE'] = pd.to_datetime(all_games['GAME_DATE'])
    three_years_ago = pd.Timestamp.now() - pd.DateOffset(years=5)
    recent_games = all_games[all_games['GAME_DATE'] > three_years_ago]
    return recent_games

# Fetch all games in the past 3 years
recent_games = fetch_games_past_3_years()

# Fetch play by play data for each game and store it in the database
from tqdm import tqdm
for index, game in tqdm(recent_games.iterrows(), total=recent_games.shape[0]):
    game_id = game['GAME_ID']
    play_by_play_data = fetch_play_by_play(game_id)
    play_by_play_data.columns = map(str.lower, play_by_play_data.columns)

    # Store the play by play data in the database
    play_by_play_data.to_sql('play_by_play_v3', engine, if_exists='append', index=False)

**Comment by pfredCL** [comment]
I'm experiencing a bug with playbyplayv3 as well, though apparently different than yours.

Actually, I think I've spotted a bug with your code:
```
def fetch_play_by_play(game_id):
    play_by_play_data = playbyplayv3.PlayByPlayV3(game_id)
    play_by_play_data = playbyplaydata.get_data_frames()[0]
    return play_by_play_data
```

Specifically in line 2 of the above function, shouldn't the line read:
`play_by_play_data = play_by_play_data.get_data_frames()[0]`

It looks like the error is being thrown a line above that so that might not change anything anyway.

Anyway, this is the error I'm experiencing with the endpoint:

### **CODE**
pbp = playbyplayv3.PlayByPlayV3(game_id=22201163)
print(pbp.get_data_frames()[0])

### **ERROR**
```
Traceback (most recent call last):
  File "c:\Users\Owner\Desktop\Code\testPy.py", line 55, in <module>
    play_by_play_data = playbyplayv3.PlayByPlayV3('22201163')
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nba_api\stats\endpoints\playbyplayv3.py", line 63, in __init__
    self.get_request()
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nba_api\stats\endpoints\playbyplayv3.py", line 73, in get_request
    self.load_response()
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nba_api\stats\endpoints\playbyplayv3.py", line 76, in load_response
    data_sets = self.nba_response.get_data_sets(self.endpoint)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nba_api\stats\library\http.py", line 150, in get_data_sets
    return endpoint_parser.get_data_sets()
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nba_api\stats\library\parserv3.py", line 309, in get_data_sets
    pbp_head = self.get_playbyplay_headers()
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nba_api\stats\library\parserv3.py", line 284, in get_playbyplay_headers
    tmp = self.nba_dict[list(self.nba_dict.keys())[1]]
IndexError: list index out of range
```
Not sure if they're related but they're both bugs with playbyplayv3 so figured I'd chime in too.

**Comment by shufinskiy** [comment]
@pfredCL, you need use full game_id:

```python
from nba_api.stats.endpoints import playbyplayv3

pbp = playbyplayv3.PlayByPlayV3(game_id='0022201163')
print(pbp.get_data_frames()[0])
```

**Comment by pfredCL** [comment]
@shufinskiy you're a lifesaver, thank you!

**Comment by rsforbes** [comment]
@equilibliam - 

I identified and fix a problem with the PlayByPlayV3 parser.

### What was happening

  While investigating your report, I discovered that the parser was using an index pattern that could break under certain conditions.

 ### What we fixed

  I've refactored the parser. Here's what changed:
```python
  Before:
  # This relied on dictionary key order
  tmp = self.nba_dict[list(self.nba_dict.keys())[1]]

  After:
  # Now uses explicit, defensive access
  self.game = nba_dict.get("game", {})
  game_id = self.game.get("gameId")
```

###  Improvements:
  - ✅ No more crashes from unexpected API responses
  - ✅ Handles missing or empty data gracefully
  - ✅ All 24 action fields explicitly defined
  - ✅ 11 new unit tests to prevent regressions
  - ✅ Tested with real game data (475 plays processed successfully!)

###  Testing

  I've verified this works with:
  - Real NBA games
  - Edge cases (missing data, empty games, etc.)
  - All existing tests still pass
